### ISSUE TITLE
ValueError: axes don't match array - Visualizing Predictions

### ISSUE THREAD

**Issue by amrit-007** [BerkeleyAutomation/sd-maskrcnn#12]
I am trying to benchmark a pre-trained model as explained here - https://github.com/BerkeleyAutomation/sd-maskrcnn by running `python tools/benchmark.py` from the /sd-maskcnn folder, and get this error on the console. The making predictions part runs well I think but the issue is when it is visualizing the predictions.

> Accumulating evaluation results...
> DONE (t=1.45s).
>  Average Precision  (AP) @[ IoU=0.5:0.05:0.95 | area=   all | maxDets=100 ] = 0.008
> 
>  Average Recall     (AR) @[ IoU=0.5:0.05:0.95 | area=   all | maxDets=100 ] = 0.004
> 
> COCO Metric Summary written to benchmark_results/pred_masks/coco_summary.txt
> VISUALIZING PREDICTIONS
>   0%|          | 0/300 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "tools/benchmark.py", line 267, in <module>
>     benchmark(config)
>   File "tools/benchmark.py", line 83, in benchmark
>     show_bbox=config['vis']['show_bbox_pred'], show_scores=config['vis']['show_scores_pred'], show_class=config['vis']['show_class_pred'])
>   File "tools/benchmark.py", line 217, in visualize_predictions
>     r['masks'] = np.transpose(r_masks, (1, 2, 0))      
>   File "/home/upsquared/amrit/fresh/venv/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 639, in transpose
>     return _wrapfunc(a, 'transpose', axes)
>   File "/home/upsquared/amrit/fresh/venv/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
>     return getattr(obj, method)(*args, **kwds)
> ValueError: axes don't match array

Please help!

**Comment by mjd3** [comment]
Hi @amrit-007, thanks for checking out the project! Can you share exactly what sequence of commands you are running so that I can attempt to reproduce this error?

**Comment by amrit-007** [comment]
hello @mjd3,

below is the file structure I have, 

> (venv) upsquared@upsquared-UP-APL01:~/amrit/sd-maskrcnn$ ls
> benchmark_results  
> data        
> maskrcnn          
> resources             
> tools
> build              
> dist
> models
> sd_maskrcnn
> cfg                
> install.sh README.md sd_maskrcnn.egg-info copyreq.txt        LICENSE     requirements.txt  setup.py


from here, i run the command, `python tools/benchmark.py`

and then I get that error.

**Comment by amrit-007** [comment]
If you look at the error message, this error is produced by the line,
`r['masks'] = np.transpose(r_masks, (1, 2, 0))`

So, then I tried printing r and r_mask and their details and this is what I got.

for 
`print r.keys()
 print r.items()`

I got, 

> ['rois', 'class_ids', 'scores']
> [('rois', array([], dtype=float64)), ('class_ids', array([], dtype=float64)), ('scores', array([], dtype=float64))]

and for 
`print r_masks.shape
 print r_masks`

I got, 

> (0,)
> [ ]

I checked for all the .npy files generated from index 000000 to 000299 in the folder benchmark_results/pred_info and benchmark_results/pred_masks and all the files are identical.

Please help.

**Comment by mjd3** [comment]
Hi @amrit-007,

I am unfortunately unable to reproduce your error on my system. Not trying to read into your `ls` too much, but it seems like you haven't downloaded the WISDOM-Real dataset to datasets/wisdom/. Have you changed the path in benchmark.yaml to point to the path where you've downloaded your dataset?

I've created a Google CoLab notebook here that gives a full example for cloning the repo and running the benchmarking script; let me know if you are able to get everything working running these commands on your machine: https://colab.research.google.com/drive/1beJu7Pjmf9JLcyNR66Btw6Hij0F2f64k.

**Comment by amrit-007** [comment]
I checked the notebook, just want to confirm the dataset needs to be downloaded to in a directory datasets/wisdom but in the root sd-maskrcnn directory or the subdirectory which goes by the same name, sd-maskrcnn?

**Comment by mjd3** [comment]
You can download the dataset wherever you want, just be sure to put the correct path to the dataset in the benchmark.yaml file. As for running without CUDA, the benchmarking will be very slow, but I got it running in this [CoLab notebook](https://colab.research.google.com/drive/1gkMfN_WDtU536N75JIRGzUTNRVOnBzla). Let me know if this works for you!
