### ISSUE TITLE
Camera range for synthetic data

### ISSUE THREAD

**Issue by karan-shr** [BerkeleyAutomation/sd-maskrcnn#19]
Hi,
While generating the synthetic data, you simulate a photoneo phoxi sensor that you had used for collecting wisdom-real. While converting the simulated depth data to images what is camera range (minZ, maxZ) used for scaling depth information to pixel vals (0, 255)?

**Comment by mjd3** [comment]
Hi @karan-shr,
The relevant code for this scaling is actually in the autolab-perception module: https://github.com/BerkeleyAutomation/perception/blob/03d9b37dd6b66896cdfe173905c9413c8c3c5df6/perception/image.py#L1513. Basically, the range of 0.25 to 1.25 in depth is scaled to the 0-255 range of a png based on the constants MIN_DEPTH and MAX_DEPTH (https://github.com/BerkeleyAutomation/perception/blob/master/perception/constants.py). That's the default behavior, but I can probably build in a way to change that if you need it!

**Comment by karan-shr** [comment]
Hi mjd3,
Sorry I forgot to respond your message...wanted to try out what you had mentioned in the message before responding to it. The info was useful. Thanks.
