### ISSUE TITLE
training whole network

### ISSUE THREAD

**Issue by frk1993** [BerkeleyAutomation/sd-maskrcnn#20]
Hello,
after creating a new synthetic dataset (with your great support) with more than 100k images, I am trying to train a new model. I have approximately 80k training images and I set the images_per_gpu = 1. I am training the network on google colab but it takes very long time. For training one epoch google colab needs 20hours.
I read in the paper that your training only took 24hours on Titan X and you had 40k training images and 60epochs. I wanted to ask you, if you were also training the whole network or only the classifier layers?

best Regards

**Comment by mjd3** [comment]
I was training the whole network; not sure about the resources on Google Colab, but I suspect that they are not quite as powerful. The images_per_gpu setting that you have will also make things very slow; I'd recommend that you increase that number to maximize the amount of images you can fit onto the GPU per batch (if this is possible on Colab). On my setup, I have images_per_gpu set to 5. One minor correction to your post above is that it takes about 24 hours for _15_ epochs with 40k training images (not 60 epochs) on my Titan X GPU.

If you are interested in not training the whole network, for example, if you want to take the pretrained weights I have here and train only the last few layers, you can change that in this area of the code: https://github.com/BerkeleyAutomation/sd-maskrcnn/blob/e30438a3ab74efa57e5de652359d3a070934d7e0/tools/train.py#L104. If you want to train the whole thing, and Google Colab isn't powerful enough, maybe try AWS?

Hope it works out! 
Mike

**Comment by frk1993** [comment]
Thank for your hints. I explored the aws and the google cloud platform. I could train my first model. But when I try to train with multiple GPUs I get following error.

<img width="899" alt="Bildschirmfoto 2019-06-29 um 23 41 08" src="https://user-images.githubusercontent.com/45715708/60492901-2a548180-9cac-11e9-9986-eef8aef5c893.png">

Thanks and best regards

**Comment by mjd3** [comment]
Ah yeah the parallel model is still broken upstream as far as I know. Here is the relevant [issue](https://github.com/matterport/Mask_RCNN/issues/1601) in the matterport/Mask_RCNN repo. Hopefully that helps! If it does work, I'd gladly accept a PR if you're willing.

**Comment by frk1993** [comment]
Hi, 
I tried to solve it but I get other errors. I am training just with one GPU. 

I have another question: i want to use additional to the depth image synthetic rgb images. In this case one image data would be 4 dimensional (rgb=3D + depth=1D). Can I do this by only changing the input_size to 4 in configuration file?

Best regards

**Comment by mjd3** [comment]
Yup it should work! Haven't tested it with 4 channel input before though, so double check the dataset.py file if it doesn't work.

**Comment by frk1993** [comment]
Thanks for your answer.

Recently I trained a new network with parameters for the realsense camera. For training I generated a new synthetic dataset with 100k (20k states) images and in average 30 objects in the bin. And I also created a real dataset with 100 realsense depth images. When I evaluate my network on this real dataset, the performance is poor. I get only ap=0.1 and ar=0.2. Its clear that I cannot get the same performance as you but isn't it too low? Do you have any hints how could I improve the performance? I am using for simulation (dataset generation) the bin which is provided by you but in real I have another bin, but I think this should not affect the performance so much. 
Here is an Image from my dataset:
![image_000022](https://user-images.githubusercontent.com/45715708/62728345-d90e7f00-ba1b-11e9-8230-5147a5fd5115.png)

**Comment by AkmaralMoldagalieva** [comment]
Hi!

How long did it take for you to train your model? what was you dataset size?

**Comment by mjd3** [comment]
@AkmaralMoldagalieva see above; took about 24 hours on a Titan Xp for me (with Intel i7 8700k 3.7 GHz CPU). Dataset size was a total of 50k 512x512 images (this [dataset](https://sites.google.com/view/wisdom-dataset/dataset_links)), with a 80/20 train/test split (so 40k training images).

**Comment by AkmaralMoldagalieva** [comment]
Thank you!
