### ISSUE TITLE
dataset generation: Unity scale error

### ISSUE THREAD

**Issue by Sean-Hastings** [BerkeleyAutomation/sd-maskrcnn#21]
On a fresh install/pull of sd-maskrcnn I encountered the following error preventing the loading of objects, breaking the generation. I have installed and used this before, however, so it is possible the issue is that someone changed the unity version on this computer.

```
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Couldn't parse vector3b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Scale should be a vector3, not single scalar. Workaround activated.
```

The full output up until I aborted it is as follows:

```
~/sd-maskrcnn$ python tools/generate_mask_dataset.py datasets/newset
Failed to load Python extension for LZ4 support. LZ4 compression will not be available.
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
WARNING:root:Unable to import pylibfreenect2. Python-only Kinect driver may not work properly.
WARNING:root:Failed to import ROS in Kinect2_sensor.py. Kinect will not be able to be used in bridged mode
WARNING:root:Unable to import Primsense sensor modules! Likely due to missing OpenNI2.
WARNING:root:Unable to import pyrealsense2.
WARNING:root:Failed to import ROS in ensenso_sensor.py. ROS functionality not available
WARNING:root:Failed to import ROS in phoxi_sensor.py. PhoXiSensor functionality unavailable.
WARNING:root:Unable to import generic sensor modules!.
pybullet build time: Jun 21 2019 11:23:09
root       INFO     Root logger now logging to datasets/newset/dataset_generation.log
tools/generate_segmask_dataset.py INFO     Creating env took 0.006 sec
tools/generate_segmask_dataset.py INFO     State: 000000
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Couldn't parse vector3b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Scale should be a vector3, not single scalar. Workaround activated.
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Couldn't parse vector3b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Scale should be a vector3, not single scalar. Workaround activated.
HeapStateSpace INFO     Sampling from train
HeapStateSpace INFO     Sampling 2 objects
tools/generate_segmask_dataset.py INFO     State: 000001
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Couldn't parse vector3b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Scale should be a vector3, not single scalar. Workaround activated.
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Couldn't parse vector3b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Scale should be a vector3, not single scalar. Workaround activated.
HeapStateSpace INFO     Sampling from train
HeapStateSpace INFO     Sampling 2 objects
tools/generate_segmask_dataset.py INFO     State: 000002
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Couldn't parse vector3b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Scale should be a vector3, not single scalar. Workaround activated.
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Couldn't parse vector3b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Scale should be a vector3, not single scalar. Workaround activated.
HeapStateSpace INFO     Sampling from train
HeapStateSpace INFO     Sampling 2 objects
tools/generate_segmask_dataset.py INFO     State: 000003
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Couldn't parse vector3b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Scale should be a vector3, not single scalar. Workaround activated.
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Couldn't parse vector3b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Scale should be a vector3, not single scalar. Workaround activated.
HeapStateSpace INFO     Sampling from train
HeapStateSpace INFO     Sampling 2 objects
tools/generate_segmask_dataset.py INFO     State: 000004
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Couldn't parse vector3b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Scale should be a vector3, not single scalar. Workaround activated.
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Couldn't parse vector3b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
Scale should be a vector3, not single scalar. Workaround activated.
HeapStateSpace INFO     Sampling from train
HeapStateSpace INFO     Sampling 2 objects
^C
```

Any ideas what may be causing this? the dataset is generated it just doesn't have any objects in the bins. If it likely is a Unity issue, what version do you use?

Thanks!

**Comment by mjd3** [comment]
Actually, this is not an error; I also get this warning (it's from pybullet/Bullet's URDF importer). Are you able to run in debug mode? You can change this line to "1" to put it into debug mode:
https://github.com/BerkeleyAutomation/sd-maskrcnn/blob/e30438a3ab74efa57e5de652359d3a070934d7e0/cfg/generate_mask_dataset.yaml#L6

Once in debug mode, you should be able to see the objects dropping one at a time and then be able to see the depth images/segmasks generated in your output folder. Let me know if that works. 

I don't think the Unity version should make a difference (I don't actually have Unity installed on my machine), but one thing that might is what renderer you are using. Do you know if you are using pyglet (default), OSMesa, or EGL? There is a known issue with OSMesa (see #15).

**Comment by Sean-Hastings** [comment]
I was actually running it in debug mode already, and the simulation window only appears for a moment before closing each time, and the saved depth_ims are all empty bins from different camera angles.

I have pyglet installed, and I imagine that is what it's using as vhacd doesn't throw up any errors. If it's any help I'm using the unchanged generate_mask_dataset.py script to do the generation.

**Comment by Sean-Hastings** [comment]
Also curious to me is the fact that it consistently samples 2 objects, which is the minimum, rather than a more random number from the distribution (mean=5, min=2, max=10)

**Comment by mjd3** [comment]
Ah so you aren't able to see the objects dropping? Unfortunately, I can't reproduce this on my setup, but if you can pinpoint where the sim window crashes, I might be of more help. Would you be able to drop a debugger into the code and determine where the debugging window crashes, then output that here?

**Comment by Sean-Hastings** [comment]
So I decided to uninstall/reinstall the project and it still shows the warning but also works now, so I guess the issue will remain a mystery. I'll try to go through the config settings and see if any one of those might have been tweaked in a way that broke it, but I don't expect that to actually work.

Oddly, the resulting depth images seem to be... not depth-y now. The following are a new generated image and an image from the wisdom-real set, respectively.

![image_000006](https://user-images.githubusercontent.com/14333392/60273964-39f75300-98c5-11e9-8d9e-6428df8a4dc1.png)

![image_000006](https://user-images.githubusercontent.com/14333392/60273967-3b288000-98c5-11e9-9cfe-3cfa7a16af43.png)
