### ISSUE TITLE
Memory Error while training

### ISSUE THREAD

**Issue by AkmaralMoldagalieva** [BerkeleyAutomation/sd-maskrcnn#25]
Hello!

I am using GeForce 1080Ti, and I have generated 5K images for training. I am running CUDA_VISIBLE_DEVICES=0 python tools/train.py  to run the training, but got memoryError. How to solve this problem? Where can I adjust batch_size?
What can you suggest me to change in order to be able to train on these 5K images?

Thank you

**Comment by frk1993** [comment]
Hey,
You can change the batch size by adjusting images_per_gpu parameter under cfg/train.yaml. 
Try images_per_gpu=2. but it depends also on your image size. What is your image size ?

**Comment by AkmaralMoldagalieva** [comment]
Hello!

Thank you for your quick response. 
Initially I had ~5k images of 512x384, but images_per_gpu = 1. 

Then I just decided to decrease my dataset, and currently training on ~1.2k images for 10 classes.
Do you think this number of images is enough for accurate detection in cluttered scene?

**Comment by frk1993** [comment]
Why did you decrease your data? I think 1.2k images for ten classes are not enough, if you train from scratch. Maybe you initialize your model with the pre-trained weights from the paper, then 1.2k images could be sufficient.

**Comment by AkmaralMoldagalieva** [comment]
Because of memory error, I was not able to go further than 6th epoch out of 20. 
Let's see the performance of my training from scratch model tomorrow. 

By the way, how can I use pre-trained weights? What part of the code should be changed? 
Thanks!

**Comment by AkmaralMoldagalieva** [comment]
Hello!

I am curious how it took 24 hours for authors to train the model with 40k synthetic images. I am using GeForce 2080Ti with 12Gb, and training on 10k synthetic images, images_per_gpu = 5. It is so slow in my case. The image size is 512x384, but resized to 512x512 due to paper. What am I doing wrong? Why training is so slow?
Thank you. I would appreciate any opinion or help.

**Comment by mjd3** [comment]
How long is it taking you to train? Our training was done on a Titan Xp for reference with the same params you referenced there.

**Comment by AkmaralMoldagalieva** [comment]
Thank you for being interested in this problem. It is solved now.

**Comment by Viky397** [comment]
Quick question: I am trying to train on my 1 NVIDIA Quadro GPU, but It gets to Epoch 1/20 and then the process says `Killed`

In train.yaml I set `images_per_gpu: 1`

Any suggestions are appreciated! Thank you!
