### ISSUE TITLE
Which mask should be used for training?

### ISSUE THREAD

**Issue by AkmaralMoldagalieva** [BerkeleyAutomation/sd-maskrcnn#26]
Hello!

I am a bit confused which mask should I use for training. In train.yaml file modal_segmask is given, but when I generated synthetic data inside the new_dataset I have: amodal_masks, modal_masks and semantic_masks. Can you give me a hint which one should be used?

**Comment by frk1993** [comment]
Hi, 
you should use semantic_maks.

**Comment by AkmaralMoldagalieva** [comment]
Thanks!
