### ISSUE TITLE
Prediction on real image without mask, just bounding box

### ISSUE THREAD

**Issue by AkmaralMoldagalieva** [BerkeleyAutomation/sd-maskrcnn#29]
Hello!

 Is it possible to get  predicted bounding boxes in real images, and how to remove mask. I want to get just bounding box and its coordinates in real image. 

Could you please provide me a hint how to do so. Thanks.

**Comment by mjd3** [comment]
Hi @AkmaralMoldagalieva! If you want to simply visualize the bounding boxes (in addition to the masks, then you can turn on the "show_bboxes_pred" flag in the benchmarking config file (https://github.com/BerkeleyAutomation/sd-maskrcnn/blob/9fabc4afa21b0375caac70ea1d77dee83145a8cc/cfg/benchmark.yaml#L31). The actual information for the bounding boxes can be found in the 'rois' field of the predictions files. Or if you're directly calling detect, then this field is part of the results that are returned (see https://github.com/BerkeleyAutomation/sd-maskrcnn/blob/9fabc4afa21b0375caac70ea1d77dee83145a8cc/tools/benchmark.py#L164). Hope that helps!

**Comment by AkmaralMoldagalieva** [comment]
Hello!

Thank you. I could get what I wanted by changing visualize.py file (diaplay_instance function). However, what is not convenient is that each time when I change the code I am compiling it with  bash /.install.sh  command, I couldn't find another way. 

Anyway, thank you for your response.

**Comment by mjd3** [comment]
Ah, you don't need to run the install script every time. If you want changes to the code to be reflected in your package install, just run ```python setup.py develop``` from the root directory of the package instead of installing it in the method used in the install script. Check this thread out: https://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install

**Comment by AkmaralMoldagalieva** [comment]
Great! Thank you!
