### ISSUE TITLE
low GPU usage

### ISSUE THREAD

**Issue by AkmaralMoldagalieva** [BerkeleyAutomation/sd-maskrcnn#30]
Hi!

I am using one GPU to train. However, the training speed is very slow.
The problem is that  the used memory of GPU is still low. I am monitoring CPU and GPU usage, sometimes CPU reaches 100%, but GPU between 1-15%. Why am I not able to use GPU fully? Maybe I need to change the image size? Any hints would be helpful. Thank you.

**Comment by joshuachang2311** [comment]
How did you solve this issue?
