### ISSUE TITLE
Precision-Recall curve

### ISSUE THREAD

**Issue by frk1993** [BerkeleyAutomation/sd-maskrcnn#35]
Hi,

How are you plotting the precision recall curves? 
I am using following code to extract values for precision recall curve at IoU 0.5:
cocoEval.eval['precision'].squeeze()[50,:,-1]

Is it right?

Thanks

**Comment by mjd3** [comment]
Hi! The precision and recall values are calculated [here](https://github.com/BerkeleyAutomation/sd-maskrcnn/blob/9fabc4afa21b0375caac70ea1d77dee83145a8cc/sd_maskrcnn/coco_benchmark.py#L193), which is consistent with what you've written (the link calculates values over the range 0.5:0.95). Do the PR curves seem to be consistent with your results?

**Comment by mjd3** [comment]
Closing this for now, reopen if there are further issues.
