### ISSUE TITLE
can i test my own dataset on your pretrained model

### ISSUE THREAD

**Issue by hanyeliu** [BerkeleyAutomation/sd-maskrcnn#37]
HI Dr mjd3:
     I have created a dataset, and i want to test it using your pre-trained  model,  do i need some addition work before test? for example, image size? batch size or something else.

**Comment by mjd3** [comment]
The pretrained model accepts 512x512 3-channel images. Batch size shouldn't matter here (by default, the benchmarking script uses a batch size of 1, but this can be modified). Note that the images I've actually used are 384x512 and are padded to 512x512, so make sure that yours are similar. If they are substantially different (or if your camera is substantially different), I'd recommend generating a dataset and training from scratch! Together, that can take a day or less (depending on your available GPU), but would give best results.

**Comment by hanyeliu** [comment]
Thanks,for your reply!
