### ISSUE TITLE
How do you convert your raw depth image to .png uint8 image?

### ISSUE THREAD

**Issue by zeal-github** [BerkeleyAutomation/sd-maskrcnn#44]
I think when generating the depth image using some simulation engine or capture in the real world, we got a depth image maybe 32bit. How do you quantize it to an 8bit png image?  How to choose the max/min depth value?

**Comment by mjd3** [comment]
Hi @zeal-github, good question! We use this [DepthImage class](https://github.com/BerkeleyAutomation/perception/blob/e1c936f38a0aef97348c2d8de364807b5238e1d0/perception/image.py#L1482). So to save a floating point depth image to a png, I would call DepthImage(fp_depth_im).save(filename). You can see the relevant max and min depth values that we used for this project [here](https://github.com/BerkeleyAutomation/perception/blob/e1c936f38a0aef97348c2d8de364807b5238e1d0/perception/constants.py#L8); note that these are automatically used when making the call to save as I did above.
