### ISSUE TITLE
Do you remove the detected boxes which contains only background pixels?

### ISSUE THREAD

**Issue by zeal-github** [BerkeleyAutomation/sd-maskrcnn#45]
Hi, sorry to bother you again. 
According to the code [here](https://github.com/BerkeleyAutomation/sd-maskrcnn/blob/75f2a81108c9e74702f831f60fcef8c5e903c8ab/tools/benchmark.py#L168-L171), if I understand correctly, in reference time:
1. send one image to the network.
2. output some detection bounding boxes and the corresponding mask.
3. for each mask->if the mask contains more than half background pixel(bin pixels, with overlap_thresh=0.5)->we remove this mask
4. for the rest masks, compute the AR and AP

Does that right?

**Comment by mjd3** [comment]
Yup that's the gist of it! Basically, from the depth image, we know if predictions are spurious so we can do the easy post-processing step of removing them.
