### ISSUE TITLE
not working on Google Colab or Local machine

### ISSUE THREAD

**Issue by ugurkanates** [BerkeleyAutomation/sd-maskrcnn#48]
Hello , due tensorflow versions(cuda 10.1 and above) won't work with this code. Could we update it to make properly work ?

**Comment by mjd3** [comment]
Hi @ugurkanates, sorry about that! I am happy to accept PRs if you want to update it to work with newer versions of TF/CUDA; unfortunately, I currently don't have the cycles and would suggest using CUDA 9.2/TF 1.12 as those are the versions that I have used most recently that work.

**Comment by ugurkanates** [comment]
Hello , sorry i fixed this problem you just need to enable TF1 (default colab is 2.0 nowadays)

`%tensorflow_version 1.x`

**Comment by mjd3** [comment]
Ah great! Didn't realize that was the case, but glad you were able to figure it out.
