### ISSUE TITLE
Quick questions on high resolution images and metric calculation

### ISSUE THREAD

**Issue by prashusat** [BerkeleyAutomation/sd-maskrcnn#49]
Hi Sir,

Thank you so much for spending your time in answering my questions.

1) I read in the paper about the result on high resolution images and low resolution images. Can you help me figure out where high resolution and low resolution images are. Are there high resolution images in real and sim datasets and low resolution real and sim datasets?

2) During the computation of metrics, how do you ensure both the ground truth and the predicted images have the same number of masks?

**Comment by mjd3** [comment]
Hi @prashusat thanks for your interest!
