### ISSUE TITLE
Output Format For --save_tensors Option

### ISSUE THREAD

**Issue by jonah-gourlay44** [BerkeleyAutomation/sd-maskrcnn#52]
Hi, I can't find documentation anywhere for the format of the output tensors when using the --save_tensors option for data generation. I was hoping you might be able to provide some clarity by letting me know what field each index in the output represents. (e.g. the output for object and camera poses is a 7-vector, what are the corresponding fields for each index in this vector?)

**Comment by mjd3** [comment]
Hey sorry about that; it is pretty unclear! The poses are actually a vector representation of the rigid transform specified [here](https://github.com/BerkeleyAutomation/autolab_core/blob/d4d288c334371a02acf9d056511b75e58eb40fe6/autolab_core/rigid_transformations.py#L235) - basically a translation vector and a quaternion. Similarly, the camera intrinsics are also a length 7 vector specified [here](https://github.com/BerkeleyAutomation/perception/blob/e1c936f38a0aef97348c2d8de364807b5238e1d0/perception/camera_intrinsics.py#L136). The other ones should be relatively straightforward (for `n` objects):
```
states:
obj_coms: (n, 3)  - translations 
obj_ids: (n,) - unique mapping from integers to meshes
image_start_ind/image_end_ind: integers saying which indices of images belong to this state
state_id: integer of state index
split: train or test bool

images:
state_ind: state index for this image
```

**Comment by jonah-gourlay44** [comment]
Awesome, no worries and thank you for your help !
