### ISSUE TITLE
Training subset of data

### ISSUE THREAD

**Issue by Viky397** [BerkeleyAutomation/sd-maskrcnn#54]
Hello, is it possible to train just a subset of the training data? Say from img000000 to img 000100?

Thank you!

**Comment by mjd3** [comment]
Yes, this can be done by changing the indices that are fed for training in the training config file (see [here](https://github.com/BerkeleyAutomation/sd-maskrcnn/blob/75f2a81108c9e74702f831f60fcef8c5e903c8ab/cfg/train.yaml#L18) for an example). You can also change the validation indices in the same part of your config file.
