### ISSUE TITLE
The requirements packages version

### ISSUE THREAD

**Issue by woshisj** [BerkeleyAutomation/sd-maskrcnn#7]
Can you show the version of package in requirements.txt?
Because the pip installation package is the latest version，I have some problems.
e.g.
 ImportError: cannot import name '_validate_lengths'
that‘s the numpy version problem
and  import pycocotools._mask as _mask
ValueError: numpy.ufunc size changed, may indicate binary incompatibility

**Comment by mmatl** [comment]
We'll update this, but for now you can just uninstall and reinstall numpy.

**Comment by woshisj** [comment]
> We'll update this, but for now you can just uninstall and reinstall numpy.
What is the version of numpy and pycocotools you installed?
The latest version of numpy has ImportError: cannot import name '_validate_lengths'
And numpy=1.15.0 has problems with File "__init__.pxd", line 918, in init pycocotools._mask ValueError: numpy.ufunc size changed,
pycocotools=2.0.0

**Comment by woshisj** [comment]
What is the version of numpy and pycocotools you installed?
The latest version of numpy has ImportError: cannot import name '_validate_lengths'
And numpy=1.15.0 has problems with File "**init**.pxd", line 918, in init pycocotools._mask ValueError: numpy.ufunc size changed,
pycocotools=2.0.0


> We'll update this, but for now you can just uninstall and reinstall numpy.

**Comment by woshisj** [comment]
I install pycocotools from source  to solve this problem instead of using pip install

**Comment by a22764288** [comment]
I use numpy==1.12
It solved 
ImportError: cannot import name '_validate_lengths' 
problem

**Comment by mjd3** [comment]
Sorry about this; stems from some incompatibility in skimage that the Mask R-CNN repo uses for resizing images. #8 addresses this issue and updates the requirements file so it should work.

**Comment by woshisj** [comment]
The numpy==1.16 have the problem
cannot import name '_validate_lengths'

> Sorry about this; stems from some incompatibility in skimage that the Mask R-CNN repo uses for resizing images. #8 addresses this issue and updates the requirements file so it should work. Please comment if you have any more issues!

**Comment by mjd3** [comment]
@woshisj be sure that you've updated your skimage version (I changed the requirement from 0.13 to 0.14). I also fixed a typo in the latest commit that may have influenced the install script. Are you running `bash install.sh`?

**Comment by woshisj** [comment]
Thank you
I installed successfully
